### PR TITLE
Feature/create activity

### PR DESCRIPTION
**Pull request by Thomas-WG**
updated:
- Activity Page: added a + button to go to manage activity page (create OK, update not yet available)
- Activity Card: correction of the mapping with attributes from Firestore
- Fetch Activity utils: added to push new activity and get a specific activity (for the update)

Added:
- Translation for the activity creation form
- manage Activity page (3 steps: type and category, basic info, sdg)
- progress stepper as component

### CODE REVIEW

**Comment by opedoussaut** [comment]
@Thomas-WG, there's probably more important comments but as I'm learning spanish right now, maybe we could consider adding spanish to the 3 languages we already have: en, fr, jp...

**Review by opedoussaut — CHANGES_REQUESTED** [review]
original: Expliquez le besoin, quand vous en avez besoin, pourquoi... Plus de détails est toujours mieux !
proposed modification: Aidez-nous à vous aider ! Décrivez votre besoin le plus précisément possible.

**Review by opedoussaut — COMMENTED** [review]
I push the code to ChatGPT, it was suggesting to merge the different types of handles to  a single HandleFormChange... it might seem to simplify the code but for us mere human it's way easier to understand the code logic when you actually see different functions, trying to understand using the function attributes if I'm handling dates, skills or whatever is not that easy...

**Comment by opedoussaut** [comment]
Another suggestion from ChatGPT that I found interesting this time as we might actually storing our categories in a DB:

To optimize the **management of categories** in your component, it's better to extract the category mapping logic into a reusable function. This keeps the component cleaner and makes the logic easier to maintain or reuse in other parts of your application.

Why Extract Categories?

Improves Readability:

- Reduces the inline complexity of the component.
- Keeps the JSX simpler by avoiding large inline mappings.

Eases Reusability:
- You can use the same logic elsewhere in your app if categories are needed.

Encourages Separation of Concerns:
- Keeps the business logic (category definitions) separate from the view logic (JSX rendering).

How to Extract Categories

**Before (Inline Mapping)**
In your current setup, categories for different types (online, local, event) are defined directly in the component and mapped inline:

```
const availableCategories = formData.type ? categories[formData.type] : [];
<ul>
    {availableCategories.map(({ id, name }) => (
        <li key={id}>
            <span>{name}</span>
        </li>
    ))}
</ul>
```
**After (Reusable Function)**
You can extract the category mapping logic into a helper function that:  

- Accepts the type as an argument.
- Returns the corresponding category list or a default list.

```
const getCategoriesByType = (type) => {
    const categories = {
        online: [
            { id: 'website', name: 'Website' },
            { id: 'translation', name: 'Translation' },
            { id: 'flyer', name: 'Flyer/Brochure' },
        ],
        local: [
            { id: 'cleaning', name: 'Cleaning' },
            { id: 'childcare', name: 'Childcare' },
        ],
        event: [
            { id: 'workshop', name: 'Workshop' },
            { id: 'conference', name: 'Conference' },
        ],
    };

    return categories[type] || [];
};
```
Using the Function in the Component
You now call getCategoriesByType inside your component and pass the type (e.g., formData.type) to retrieve the categories dynamically.

```
const availableCategories = getCategoriesByType(formData.type);

<ul className="grid grid-cols-3">
    {availableCategories.map(({ id, name }) => (
        <li
            key={id}
            className={`p-2 border ${
                formData.category === id ? 'bg-orange-500 text-white' : 'bg-white text-black'
            }`}
            onClick={() => handleFormChange('category', id)}
        >
            {name}
        </li>
    ))}
</ul>
```

**Benefits**

Centralized Logic:
- All category mappings are now in one place, making it easy to update or debug.

Cleaner JSX:
- The component's JSX no longer contains repetitive mapping logic, improving readability.

Reusability:
- You can reuse getCategoriesByType in other components or contexts (e.g., an API endpoint or dropdown menu).

**Further Optimization**
If categories are extensive or fetched from a backend, consider:  

- Storing Categories in a Database.
- Fetch categories dynamically using an API call.
- Cache them in state for subsequent use.

Memoizing the Function:  Use useMemo to prevent recalculating categories on every render:
`const availableCategories = useMemo(() => getCategoriesByType(formData.type), [formData.type]);`

This approach keeps your component lightweight and focused on rendering, while the logic for categories remains reusable and maintainable!

**Comment by Thomas-WG** [comment]
I added a new commit based on your feedbacks:
- Added Spanish language translation
- Separated the file for the categories. It is in constant/categories.js
==> I haven’t put them in the DB as we don’t need to change them that often and still need to update the translation files if we want to add or remove categories. Let’s see in the future if we want to put them in the DB but for the MVP I think it should be ok.

**Pull request merged**
