### PR TITLE
Feature/internationalization

### PR DESCRIPTION
**Pull request by Thomas-WG**
Added the internationalization services, which is managing a cookie with the preferred language of the users from the Settings page. Default is "en".

### CODE REVIEW

**Comment by opedoussaut** [comment]
@Thomas-WG , sorry for the late reaction, I was preparing our first EECONE webinar, can I delete the branch as you have committed your feature or do we keep it in case you have some modifications to make to that feature ?

**Comment by Thomas-WG** [comment]
No worries, I guessed you were busy. I just needed the translation in my current branch so I can apply it in the create activity page. Yes you can delete the branch.

**Comment by opedoussaut** [comment]
Done... you're coding too fast for me ;-)

**Comment by Thomas-WG** [comment]
You’re not ready for what’s coming soon :)

**Comment by opedoussaut** [comment]
> You’re not ready for what’s coming soon :)

Bring the good news, I'm ready ;-)

**Comment by Thomas-WG** [comment]
~500 new lines of code for now, for create update an activity.

**Pull request merged**
